packages:
  - apps/*
  - packages/*

catalog:
  "next": "15.5.9"
  "@types/react": "19.1.8"
  "@types/react-dom": "19.1.6"
  "typescript": "5.7.3"
  "react": "19.1.0"
  "react-dom": "19.1.0"
  "motion": "^12.23.25"
  "tailwindcss": "^4.1.16"
  "@types/node": "^22.5.4"
  "zod": "^4.1.13"
  "@t3-oss/env-core": "^0.13.8"
  "@t3-oss/env-nextjs": "^0.13.8"

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp
