/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    articles: Article;
    'news-feat': NewsFeat;
    tags: Tag;
    issues: Issue;
    activities: Activity;
    'map-zones': MapZone;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'news-feat': NewsFeatSelect<false> | NewsFeatSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'map-zones': MapZonesSelect<false> | MapZonesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ta-IN') | ('en' | 'ta-IN')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'ta-IN';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username?: string | null;
  roles?: ('admin' | 'content-manager' | 'user')[] | null;
  /**
   * Inactive users cannot login
   */
  isActive?: boolean | null;
  /**
   * Last successful login timestamp
   */
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  /**
   * Auto generated url of the blurred version of the image, can be used for placeholder loading in Nextjs Image.
   */
  blurDataUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    blur?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Brief summary. Used as SEO description fallback.
   */
  excerpt?: string | null;
  hero?:
    | (
        | {
            title: string;
            centerImg: number | Media;
            bgImg?: (number | null) | Media;
            bgText: string;
            content?:
              | {
                  para: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'parallax-hero';
          }
        | CutoutHero
        | {
            title: string;
            bgImg?: (number | null) | Media;
            breadcrumb?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'minimal-hero';
          }
      )[]
    | null;
  layout?:
    | (
        | {
            bgImg: number | Media;
            /**
             * The text overlay on top of image
             */
            headline: string;
            variant?: ('midnight' | 'blue' | 'light') | null;
            title: string;
            description?:
              | {
                  para: string;
                  id?: string | null;
                }[]
              | null;
            hls?: {
              title?: string | null;
              tImg?: (number | null) | Media;
              wImg?: (number | null) | Media;
              sBlk?:
                | {
                    title: string;
                    desc: string;
                    stats?:
                      | {
                          v: string;
                          l: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'sticky-stats';
          }
        | {
            showHeading?: boolean | null;
            heading?: string | null;
            /**
             * Which tab opens by default
             */
            defType: 'announcements' | 'articles' | 'news-feat';
            showTags?: boolean | null;
            showCta?: boolean | null;
            /**
             * Number of items to show per page
             */
            perPage: number;
            /**
             * Which content types to show as tabs
             */
            enabled: ('announcements' | 'articles' | 'news-feat')[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'latest-updates';
          }
        | CompositeGridBlock
        | TimelineBlock
        | TabbedContentBlock
        | InteractiveMapBlock
        | SocialMediaBlock
      )[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CutoutHero".
 */
export interface CutoutHero {
  title: string;
  desc: string;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    /**
     * Optional: Add # to scroll to a section (e.g., "team" for #team)
     */
    anchor?: string | null;
    label: string;
  };
  portraits?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  bgImg?: (number | null) | Media;
  cutout?: (number | null) | Media;
  stats?:
    | {
        l: string;
        v: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cutout-hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompositeGridBlock".
 */
export interface CompositeGridBlock {
  heading: string;
  description?: string | null;
  bgImg?: (number | null) | Media;
  items?:
    | {
        cardType: 'image' | 'content';
        imageCard?: {
          image: number | Media;
        };
        contentCard?: {
          title: string;
          text: string;
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            /**
             * Optional: Add # to scroll to a section (e.g., "team" for #team)
             */
            anchor?: string | null;
            label: string;
          };
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comp-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  heading: string;
  tagLine?: string | null;
  items?:
    | {
        year: string;
        image?: (number | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock".
 */
export interface TabbedContentBlock {
  heading: string;
  description: string;
  bgImg?: (number | null) | Media;
  tabs?:
    | {
        label: string;
        image: number | Media;
        logo: number | Media;
        description: string;
        stats?:
          | {
              v: string;
              l: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tab-content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractiveMapBlock".
 */
export interface InteractiveMapBlock {
  title?: string | null;
  description?: string | null;
  /**
   * Summary mode shows a simplified view. Full mode allows deep linking.
   */
  mode?: ('summary' | 'full') | null;
  headline?: string | null;
  knowMoreLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
    /**
     * Optional: Add # to scroll to a section (e.g., "team" for #team)
     */
    anchor?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'int-map';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMediaBlock".
 */
export interface SocialMediaBlock {
  heading?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'twitter' | 'facebook' | 'youtube' | 'linkedin' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'social-media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Brief title or headline of the article
   */
  title: string;
  image: number | Media;
  tags: number | Tag;
  /**
   * Name of newspaper (e.g., "The Hindu", "Times of India")
   */
  newspaper?: string | null;
  publishedDate: string;
  /**
   * Optional: Link to online version of article
   */
  externalLink?: string | null;
  /**
   * Should this album be visible to the public?
   */
  isFeat?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  label: string;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Display order (lower numbers first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-feat".
 */
export interface NewsFeat {
  id: number;
  /**
   * Brief title or headline of the feature
   */
  title: string;
  /**
   * Name of newspaper (e.g., "The Hindu", "Times of India")
   */
  newspaper?: string | null;
  image: number | Media;
  tags: number | Tag;
  publishedDate: string;
  /**
   * Optional: Link to online version of article
   */
  externalLink?: string | null;
  /**
   * Should this album be visible to the public?
   */
  isFeat?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  icon?: (number | null) | Media;
  color?: ('blue' | 'yellow' | 'neutral') | null;
  overlayType?: ('solid' | 'gradient') | null;
  /**
   * Should this album be visible to the public?
   */
  isFeat?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  cost: number;
  type?: (number | null) | Issue;
  zone?: (number | null) | MapZone;
  scheme?: string | null;
  financialYear?: string | null;
  status?: ('planned' | 'in-progress' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-zones".
 */
export interface MapZone {
  id: number;
  /**
   * The name shown in the tooltip and header (e.g., "Ward 160" or "Iyyappanthangal")
   */
  name: string;
  slug?: string | null;
  slugLock?: boolean | null;
  type: 'panchayat' | 'ward';
  /**
   * Approximate population
   */
  population?: number | null;
  areaSqKm?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'news-feat';
        value: number | NewsFeat;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'issues';
        value: number | Issue;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'map-zones';
        value: number | MapZone;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  roles?: T;
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        blur?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  hero?:
    | T
    | {
        'parallax-hero'?:
          | T
          | {
              title?: T;
              centerImg?: T;
              bgImg?: T;
              bgText?: T;
              content?:
                | T
                | {
                    para?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cutout-hero'?: T | CutoutHeroSelect<T>;
        'minimal-hero'?:
          | T
          | {
              title?: T;
              bgImg?: T;
              breadcrumb?: T;
              id?: T;
              blockName?: T;
            };
      };
  layout?:
    | T
    | {
        'sticky-stats'?:
          | T
          | {
              bgImg?: T;
              headline?: T;
              variant?: T;
              title?: T;
              description?:
                | T
                | {
                    para?: T;
                    id?: T;
                  };
              hls?:
                | T
                | {
                    title?: T;
                    tImg?: T;
                    wImg?: T;
                    sBlk?:
                      | T
                      | {
                          title?: T;
                          desc?: T;
                          stats?:
                            | T
                            | {
                                v?: T;
                                l?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'latest-updates'?:
          | T
          | {
              showHeading?: T;
              heading?: T;
              defType?: T;
              showTags?: T;
              showCta?: T;
              perPage?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        'comp-grid'?: T | CompositeGridBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        'tab-content'?: T | TabbedContentBlockSelect<T>;
        'int-map'?: T | InteractiveMapBlockSelect<T>;
        'social-media'?: T | SocialMediaBlockSelect<T>;
      };
  slug?: T;
  slugLock?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CutoutHero_select".
 */
export interface CutoutHeroSelect<T extends boolean = true> {
  title?: T;
  desc?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        anchor?: T;
        label?: T;
      };
  portraits?:
    | T
    | {
        image?: T;
        id?: T;
      };
  bgImg?: T;
  cutout?: T;
  stats?:
    | T
    | {
        l?: T;
        v?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompositeGridBlock_select".
 */
export interface CompositeGridBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  bgImg?: T;
  items?:
    | T
    | {
        cardType?: T;
        imageCard?:
          | T
          | {
              image?: T;
            };
        contentCard?:
          | T
          | {
              title?: T;
              text?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    anchor?: T;
                    label?: T;
                  };
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  heading?: T;
  tagLine?: T;
  items?:
    | T
    | {
        year?: T;
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock_select".
 */
export interface TabbedContentBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  bgImg?: T;
  tabs?:
    | T
    | {
        label?: T;
        image?: T;
        logo?: T;
        description?: T;
        stats?:
          | T
          | {
              v?: T;
              l?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InteractiveMapBlock_select".
 */
export interface InteractiveMapBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  mode?: T;
  headline?: T;
  knowMoreLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        anchor?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMediaBlock_select".
 */
export interface SocialMediaBlockSelect<T extends boolean = true> {
  heading?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  tags?: T;
  newspaper?: T;
  publishedDate?: T;
  externalLink?: T;
  isFeat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-feat_select".
 */
export interface NewsFeatSelect<T extends boolean = true> {
  title?: T;
  newspaper?: T;
  image?: T;
  tags?: T;
  publishedDate?: T;
  externalLink?: T;
  isFeat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  slugLock?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  icon?: T;
  color?: T;
  overlayType?: T;
  isFeat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  cost?: T;
  type?: T;
  zone?: T;
  scheme?: T;
  financialYear?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-zones_select".
 */
export interface MapZonesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slugLock?: T;
  type?: T;
  population?: T;
  areaSqKm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          /**
           * Optional: Add # to scroll to a section (e.g., "team" for #team)
           */
          anchor?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  title: string;
  desc: string;
  bgImg?: (number | null) | Media;
  socialLinks?:
    | {
        platform: 'instagram' | 'twitter' | 'facebook' | 'youtube' | 'linkedin' | 'github';
        id?: string | null;
      }[]
    | null;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          /**
           * Optional: Add # to scroll to a section (e.g., "team" for #team)
           */
          anchor?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              anchor?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  desc?: T;
  bgImg?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              anchor?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}